# conda env create --file environment.yml
# mamba env create --file environment.yml
name: genetic_ant-colony-optimization_transport
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
  - pip
  - pyjanitor
  - pylint
  - pyprojroot
  - pathlib
  - pyspark
  - python=3.7
  - python-dotenv
  - seaborn
  - plotly
  - deap
  - random